// <auto-generated />
using System;
using E_Shop.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;

namespace EShop.Migrations {
    [DbContext (typeof (EShopContext))]
    [Migration ("20180302211316_InitialMigration")]
    partial class InitialMigration {
        protected override void BuildTargetModel (ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation ("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation ("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity ("E_Shop.Models.Order", b => {
                b.Property<int> ("OrderId")
                    .ValueGeneratedOnAdd ();

                b.Property<int> ("UserId");

                b.HasKey ("OrderId");

                b.HasIndex ("UserId");

                b.ToTable ("Orders");
            });

            modelBuilder.Entity ("E_Shop.Models.Product", b => {
                b.Property<int> ("ProductId")
                    .ValueGeneratedOnAdd ();

                b.Property<string> ("Description");

                b.Property<int?> ("OrderId");

                b.Property<decimal> ("Price");

                b.Property<string> ("ProductName");

                b.Property<string> ("PruductImageUrl");

                b.Property<int> ("Stock");

                b.HasKey ("ProductId");

                b.HasIndex ("OrderId");

                b.ToTable ("Products");
            });

            modelBuilder.Entity ("E_Shop.Models.User", b => {
                b.Property<int> ("UserId")
                    .ValueGeneratedOnAdd ();

                b.Property<string> ("FirstName");

                b.Property<string> ("LastName");

                b.Property<string> ("Mail");

                b.Property<decimal> ("PhoneNumber");

                b.HasKey ("UserId");

                b.ToTable ("Users");
            });

            modelBuilder.Entity ("E_Shop.Models.Order", b => {
                b.HasOne ("E_Shop.Models.User", "User")
                    .WithMany ()
                    .HasForeignKey ("UserId")
                    .OnDelete (DeleteBehavior.Cascade);
            });

            modelBuilder.Entity ("E_Shop.Models.Product", b => {
                b.HasOne ("E_Shop.Models.Order")
                    .WithMany ("Products")
                    .HasForeignKey ("OrderId");
            });
#pragma warning restore 612, 618
        }
    }
}